-- Archivo: src/main/resources/schema.sql

-- Crear secuencia para el ID si no existe
CREATE SEQUENCE IF NOT EXISTS PSER_SEQ_MDD_REPORTE START WITH 1 INCREMENT BY 1;

-- Crear tabla si no existe
CREATE TABLE IF NOT EXISTS PSER_TB_MDD_REPORTE (
    ID_BITACORA_REPORTE_MDD NUMBER(16,0) PRIMARY KEY,
    CH_TIPO_REPORTE VARCHAR2(25),
    FC_INICIO_PROCESO TIMESTAMP,
    FC_FIN_PROCESO TIMESTAMP,
    NU_ESTATUS NUMBER(1,0) NOT NULL,
    CH_TIPO_CONSULTA VARCHAR2(100),
    FC_CONTROL TIMESTAMP NOT NULL,
    CH_USUARIO_MODIFICADOR VARCHAR2(50),
    CH_NODO_EJECUTOR VARCHAR2(100),
    FC_BLOQUEO TIMESTAMP,
    FC_EXPIRACION_BLOQUEO TIMESTAMP
);

-- Crear índices si no existen
CREATE INDEX IF NOT EXISTS IDX_MDD_ESTATUS_FECHA ON PSER_TB_MDD_REPORTE(NU_ESTATUS, FC_CONTROL);
CREATE INDEX IF NOT EXISTS IDX_MDD_EXPIRACION ON PSER_TB_MDD_REPORTE(FC_EXPIRACION_BLOQUEO);

-- Insertar algunos datos de ejemplo
-- Solo ejecutará si la tabla está vacía
INSERT INTO PSER_TB_MDD_REPORTE (
    ID_BITACORA_REPORTE_MDD, 
    CH_TIPO_REPORTE, 
    NU_ESTATUS, 
    CH_TIPO_CONSULTA, 
    FC_CONTROL, 
    CH_USUARIO_MODIFICADOR
)
SELECT 
    NEXT VALUE FOR PSER_SEQ_MDD_REPORTE, 
    'REPORTE_DIARIO', 
    0, 
    'CONSULTA_GENERAL', 
    CURRENT_TIMESTAMP(), 
    'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PSER_TB_MDD_REPORTE);